[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
evm_version = "paris"

# Testing
fuzz_runs = 256
invariant_runs = 256
test_timeout = 60000

# Verbosity
verbosity = 1
gas_reports = ["FallbackDemo"]

# Extra output
extra_output = ["metadata", "storageLayout", "evm.assembly"]

# Testing options
fuzz_max_test_rejects = 50000
fuzz_seed = "12345"

# Formatting (âš  FIXED)
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
quote_style = "double"

# Optimizer
optimizer = true
optimizer_runs = 200

# Metadata
bytecode_hash = "ipfs"

[profile.ci]
src = ["src"]
test = ["test"]
script = ["script"]
